name: sysfoo-pipeline 
on:
  push:
    branches:
      - 'master'
jobs:
  sysfoo-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: sysfoo-pipeline
        run: echo "Welcome to sysfoo ci pipeline"

      - name: code-checkout
        uses: actions/checkout@v6

      - name: mvn test
        run: mvn test

      - name: mvn-package-clean
        run: mvn clean

      - name: mvn-package
        run: mvn package

      - name: list-files
        run: ls -lrt target

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: sysfoo-artifact
          path: target/**.war

      
