name: sysfoo-pipeline 
on: [push]
jobs:
  sysfoo-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: sysfoo-pipeline
        run: echo "Welcome to sysfoo ci pipeline"

      - name: code-checkout
        uses: actions/checkout@v6

      - name: mvn test
        run: mvn-test

      - name: mvn-package-clean
        run: mvn clean

      - name: mvn-package
        run: mvn package

      - name: list-files
        run: ls -lrt target
